export const HOME = "Home";
export const FIRST_NAME = "First name";
export const LAST_NAME = "Last name";
export const MOBILE_NUMBER = "Mobile number";
export const EMAIL_ID = "Email id";
export const LOADING = "Loading ...";
export const ACTIONS = "Actions";
export const ADD_STUDENT = "Add Student" 
export const NO_DATA = "No data"
export const SUBMIT = "Submit" 
export const MODIFY = "Modify" 
export const EDIT_DATA = "Edit data"